### ISSUE TITLE
[BUG] Meta issue: Cython 0.29.x is not compatible with Python 3.10

### ISSUE THREAD

**Issue by vstinner** [cython/cython#4046]
I created the issue as a meta issue for Cython 0.29.x compatibility issues with Python 3.10.

Bugs:

* [x] #3919: Tests failing on Python 3.10: annotations as string and no more empty frozenset singleton
* [x] ~~#4025: Cython 0.29.22 SIGSEGV with Python 3.10.0a6 #4025~~

Fixes:

* [x] #4042: Port test_exceptions to Python 3.10
* [x] #4044: Port test_asyncgen to Python 3.10
* [x] #4045: Make load_dynamic() compatible with Python 3.10

See also #4027 ( Decimal module C API) and #4029 (Structural Pattern Matching) which are feature requests, not compatibility issues.

**Comment by vstinner** [comment]
Fedora downstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1939885

**Comment by scoder** [comment]
All issues closed and PRs merged.
