### ISSUE TITLE
[BUG] remaining bugs with `cpp_locals` directive

### ISSUE THREAD

**Issue by da-woods** [cython/cython#4266]
The following tests fail when `cpp_locals` is enabled:

- [x] `run/cpp_operators` - this is to do with `generate_bool_evaluation_code`, which works in quite a non-standard way to perform short-circuiting.
- [x] `run/cpp_vector_in_generator` - iteration?  Fixed in https://github.com/cython/cython/pull/4265
- [x] `run/cpp_stl_string` - iteration? #4265
- [x] `compile/cpp_temp_assignment` - closures #4265
- [x] `run/fused_cpp` - not sure but it involves typeid so probably just needs special-casing
- [x] `run/if_else_expr_cpp` - to  do with fakereferences #4265
- [x] `errors/w_uninitialized_cpp` - typeid again
